# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT-29th-JointSeminar10-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT-29th-JointSeminar10-iOS
pod 'Alamofire', '~> 5.4'
pod 'RxSwift', '6.2.0'
pod 'RxCocoa', '6.2.0'
pod 'Kingfisher', '~> 7.0'
end
